### ISSUE TITLE
"Cannot load bp-group-tags." when adding a new group tag

### ISSUE THREAD

**Issue by RamiTITG** [imath/bp-groups-taxo#8] opened 2015-12-31 13:52 UTC
Hello!, I saw today a permission problem when accessing the bp group taxo menu in wp-admin and I found someone reported it here and you made some changes these past few weeks. However I have now a "Cannot load bp-group-tags." when I add a new label and click "Save".

I'm able to use and edit all existing labels, the error appears to happen when you try to create a new label.

Thanks!
Rami

**Comment by imath** [comment] 2016-01-06 13:22
Found a similar problem when on a multisite config.. But wasn't able to reproduce your trouble what is your config ?

WordPress version ? BuddyPress version ? Multisite ?

**Comment by RamiTITG** [comment] 2016-01-07 21:34
Hello imath, thanks for your reply. I was about to reply to you now, but I made these last changes you made yesterday, and now I don't have that error anymore. The tag is created without any troubles. Thanks!!!

**Comment by pointofmercy** [comment] 2016-03-04 20:52
@imath Hello! 

I just recently heard about this plugin and installed. Very cool concept! I am running into the same issue that you discovered.  I'm using WP 4.4.2, BP 2.5.0, Multisite Configuration. 

Plugin is Network Activated. In fact, plugin doesn't work unless network activated.  I assume because my buddypress is multisite enabled, as well.

I see the group tags, can create group tags, but can not associate with group. All i see is the "No tags have been set, you can define tags from the Group Tags Administration" under Manage Tags.

Thanks!

**Comment by pointofmercy** [comment] 2016-03-08 13:54
Hello @imath 

Just seeing if you have found the same issue i have with the plugin.

Thanks!

**Comment by imath** [comment] 2016-03-08 20:26
@pointofmercy 

FYI: Network administration doesn't include the needed files to manage tags. So this plugin is doing some acrobatics to bring it. I'll merge branch beta-3 with master in a few seconds and it should solve your issue.

Many thanks to @RamiTITG who confirmed things were fixed in this branch.

I'll open a new branch, because things are changing in WordPress 4.5... Using this plugin in a multisite having BuddyPress activated on the network is really complex...

**Closed** 2016-03-08 20:30 UTC
